<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Create New Banner</h4>
    </div>
    <fieldset>
        <button class="scalable add" type="button" title="Create New Banner" onclick="setLocation('<?php echo $this->getUrl('*/adminhtml_banner/new', array('groupid' => $this->getRequest()->getParam('id'))); ?>')"><span><span>Create New Banner</span></span></button>
    </fieldset>
</div>